### ISSUE TITLE
Multisite support?

### ISSUE THREAD

**Issue by stuartmaxwell** [elightup/slim-seo#1]
Thanks for the work on this project. Should this plugin work for multisite installations too? I have installed the plugin and network activated it but the sitemap was only created on the primary blog and not the other sites in the network. I also tried moving the plugin to the "must-use" plugin directory and it still only worked for the primary blog. Before I troubleshoot this further I was wondering if you had tested this in a multisite setup and if you expect that it should work?

**Comment by rilwis** [comment]
Hi @stuartmaxwell,

The plugin should work in Multisite environment. Let me check the sitemap again.

**Comment by stuartmaxwell** [comment]
Ah - you're right. Just clicking the "Save changes" button in the Permalink Settings fixes it. Any idea why this is happening and can it be fixed without manually refreshing the permalink settings on all blogs (I have 2000+ blogs...)

**Comment by stuartmaxwell** [comment]
Currently running the following command across my multisite which will flush the rewrite structure for all blogs:
`wp site list --field=url | xargs -n1 -I % wp rewrite flush --url=%`

Perhaps this plugin could flush the rewrite rules automatically when it's activated? Not sure how easy/hard that is to achieve.

**Comment by rilwis** [comment]
Thanks a lot for your `wp-cli` command.

The plugin added rewrite rules for sitemaps, so it's required to flush the rules. I'll try to do this automatically when the plugin is activated.

**Comment by rilwis** [comment]
Fixed in https://github.com/elightup/slim-seo/commit/155862a5bccbcfcae7664a1fd905a459a86cadf3
