### ISSUE TITLE
Deprecation warning in link format

### ISSUE THREAD

**Issue by jstask82** [elightup/slim-seo#108]
I noticed Slim SEO replaces the core/link format in RichText Components, causing a deprecation warning
```
useAnchorRef` hook is deprecated since version 6.1. Please use `useAnchor` hook instead. 
    at  ...plugins/slim-seo/js/link-attributes/block-editor/dist/index.js?ver=d987f01638a1f0146ba9:1:10964
```

**Comment by rilwis** [comment]
The purpose of link-attribute JS is for adding nofollow when inserting links. This is now available in the block editor, so the script is no longer needed. I've just removed it here 0845fd30e1d07c0845fc093fa4818f8d301901ad .
