### ISSUE TITLE
Suggestion: add a link to the sitemap on the settings page

### ISSUE THREAD

**Issue by erikjoling** [elightup/slim-seo#110]
I would like to suggest adding a link to the websites sitemap on the settings page of Slim SEO. 

Currently there is just a toggle on the settings page to turn on/off sitemaps with some minor information added. I had to go to the documents to find out what the link is to the sitemap (domain.com/sitemap.xml of course... :stuck_out_tongue_closed_eyes: ). It would be nice to have a link added there so I can directly check out my sitemap. 

I appreciate your plugin by the way. Thanks for sharing your work with the world :pray:

**Comment by rilwis** [comment]
Thanks for your suggestion. We've just updated the style for the Features tab to show details about each feature, and also show the link to the sitemap.
