### ISSUE TITLE
Consider adding structured data markup for breadcrumbs

### ISSUE THREAD

**Issue by SampoVirmasalo** [elightup/slim-seo#116]
Hi!

Currently breadcrumb-shortcode adds basic nav-element where called:
```html
<nav class="breadcrumbs" aria-label="Breadcrumbs">
  <a href="http://localhost:10074/" class="breadcrumb breadcrumb--first">Home</a> 
  <span class="breadcrumbs__separator" aria-hidden="true">»</span> 
  <span class="breadcrumb breadcrumb--last" aria-current="page">Sample page</span>
</nav>
```

This feature would be better with proper structured data markup.

Google reference: [https://developers.google.com/search/docs/appearance/structured-data/breadcrumb](https://developers.google.com/search/docs/appearance/structured-data/breadcrumb)

**Comment by rilwis** [comment]
Hi,

Breadcrumbs has [its own schema](https://github.com/elightup/slim-seo/blob/master/src/Schema/Types/BreadcrumbList.php) in the JSON-LD format. We don't implement schema markup directly in the HTML output to avoid any conflicts and to make it easier to style.
