### ISSUE TITLE
Meta description of password protected posts

### ISSUE THREAD

**Issue by erikjoling** [elightup/slim-seo#12]
Hi,

First of all, thanks for developing, open-sourcing and maintaining this wonderful plugin.

I have an issue regarding to password protected posts. The unprotected meta description is shown when I would expect a message that the post is protected.

In the `get_singular_value` method of the Description class `get_the_excerpt($post_id)` should be used in stead of directly addressing `$post->post_excerpt`.

**Comment by erikjoling** [comment]
I tried to create a pull request: #13

**Comment by rilwis** [comment]
Thank you for your help! I think it's good to not show the description for password protect posts. Let's discuss more in the PR.
