### ISSUE TITLE
500 links per file is not enough

### ISSUE THREAD

**Issue by maximejobin** [elightup/slim-seo#14]
Great plugin... just discovered it and like how simple it is.

I see, in your doc and code, that you put only 500 links per sitemap citing this Google link:
https://support.google.com/webmasters/answer/75712

This page says nothing about "500 links". It says: 

> You can submit up to 500 sitemap index files for each site in your account.

I've had sites with millions of pages and the real answer is 50,000 URLs per file.

Here is what Google has to say about building sitemaps:

> All formats limit a single sitemap to 50MB (uncompressed) and 50,000 URLs. If you have a larger file or more URLs, you will have to break your list into multiple sitemaps. You can optionally create a sitemap index file (a file that points to a list of sitemaps) and submit that single index file to Google. You can submit multiple sitemaps and/or sitemap index files to Google.

_Source: https://support.google.com/webmasters/answer/183668_

I hope this helps make the plugin better.

**Comment by rilwis** [comment]
Hi @maximejobin,

Thanks for your correction! You're right about the 50k URLs instead of 500. I'll increase the limit for the sitemap.

Just a small question: in your case of million URLs, did you put 50k URLs in a sitemap? Does that effect the performance?

**Comment by maximejobin** [comment]
> in your case of million URLs, did you put 50k URLs in a sitemap?

Correct. We did generate each file with 50k URLs and then gzip them (one file per gzip).

Does that effect the performance?

This cannot be done "on the fly". We had a process that would run to generate mega lists in an optimal way. That is not easy in your case if because you have no context because all sites are different. You may have to do "counts" to know if you can generate everything in one process or if you'll have to split the URLs in multiple files.

**Comment by rilwis** [comment]
@maximejobin : I increased the number of links in the sitemap to 2000, similar to what WP does in the Core (FYI: sitemap is going to be added in WP Core in version 5.5). I also added filters to change the query args, in case users want to change that number (and other query args).
