### ISSUE TITLE
Allow custom sitemap slug

### ISSUE THREAD

**Issue by wpsumo** [elightup/slim-seo#142]
I want a cleaner sitemap structure.

Could you allow us to customize it to what ever we want?

Right now:
sitemap-post-type-page.xml

What I may want:
sitemap-page.xml
sitemap-pages.xml
pages.xml

**Comment by rilwis** [comment]
Unfortunately, the slugs are fixed in the plugin because:

1. It relates to how the rewrite rules are generated and are parsed. Changing it requires a *very* complicated parser.
2. It's a technical bit and is used for search engines only. It doesn't affect SEO if changing the slugs.
