### ISSUE TITLE
Adjustable meta for special pages (seo title and description, meta robots)

### ISSUE THREAD

**Issue by wpsumo** [elightup/slim-seo#143]
I cannot find in the documentation how to specify a custom title and description and meta robots for special pages like, search, archive, 404 page etc.

**Comment by rilwis** [comment]
- Search & 404 pages are not indexed, so changing meta title & description is not necessary for SEO.
- For archive pages, we have settings for post type archives. We're working on improving the settings for other archives such as author or date archives.

In any case, you still can use our filters to [change meta title](https://docs.wpslimseo.com/slim-seo/meta-title-tag/#how-to-change-the-meta-title-with-code) and [meta description](https://docs.wpslimseo.com/slim-seo/meta-description-tag/#how-to-change-the-meta-description).

**Comment by wpsumo** [comment]
@rilwis don't agree it's only for SEO you may want it for branding and uniqueness and not look like everyone else it make sense to allow us to customize please make it available in UI but if not in code and support multilingual

**Comment by wpsumo** [comment]
@rilwis any update?

**Comment by rilwis** [comment]
Things are under progress here #146

**Comment by wpsumo** [comment]
@rilwis Will you add hook or in the GUI to edit search and 404 meta? its also for branding purposes people want to customize it.

**Comment by rilwis** [comment]
Yes, there are hooks for [meta title](https://docs.wpslimseo.com/slim-seo/meta-title-tag/#how-to-change-the-meta-title-with-code) and [meta description](https://docs.wpslimseo.com/slim-seo/meta-description-tag/#how-to-change-the-meta-description) in our docs.
