### ISSUE TITLE
Disabling Breadcrumbs in Settings disables Elementor page builder editing mode.

### ISSUE THREAD

**Issue by jetcraft-io** [elightup/slim-seo#170]
Dear Slim SEO.
Firstly, Thank you for your service always.

After your recent update to version 4.1.0, a critical error occurs when disabling(Uncecked toggle) the Breadcrumbs feature in the plugin settings, preventing access to the post editing screen of the Elementor Page Builder and many error occured with used javascript in web page. Below is the debug message output from the Elementor builder for your reference.

----

Notice: Trying to access array offset on value of type null in /var/www/html/wp-content/plugins/slim-seo/src/Breadcrumbs.php on line 111 Fatal error: Uncaught TypeError: Argument 2 passed to SlimSEO\Breadcrumbs::add_link() must be of the type string, null given, called in /var/www/html/wp-content/plugins/slim-seo/src/Breadcrumbs.php on line 111 and defined in /var/www/html/wp-content/plugins/slim-seo/src/Breadcrumbs.php:229 Stack trace: #0 /var/www/html/wp-content/plugins/slim-seo/src/Breadcrumbs.php(111): SlimSEO\Breadcrumbs->add_link('https://jetcraf...', NULL) #1 /var/www/html/wp-content/plugins/slim-seo/src/Schema/Types/BreadcrumbList.php(12): SlimSEO\Breadcrumbs->parse() #2 /var/www/html/wp-content/plugins/slim-seo/src/Schema/Types/Base.php(41): SlimSEO\Schema\Types\BreadcrumbList->is_active() #3 /var/www/html/wp-content/plugins/slim-seo/src/Schema/Manager.php(75): SlimSEO\Schema\Types\Base->add_reference('breadcrumb', Object(SlimSEO\Schema\Types\BreadcrumbList)) #4 /var/www/html/wp-content/plugins/slim-seo/src/Schema/Manager.php(30): SlimSEO\Schema\Manager->add_schemas() #5 /var/www/html/wp-includes/class-wp-hook.php(324): SlimSEO\Schema\Manager->out in /var/www/html/wp-content/plugins/slim-seo/src/Breadcrumbs.php on line 229
Uncaught TypeError: Argument 2 passed to SlimSEO\Breadcrumbs::add_link() must be of the type string, null given, called in /var/www/html/wp-content/plugins/slim-seo/src/Breadcrumbs.php on line 111 and defined in /var/www/html/wp-content/plugins/slim-seo/src/Breadcrumbs.php:229
Stack trace:
#0 /var/www/html/wp-content/plugins/slim-seo/src/Breadcrumbs.php(111): SlimSEO\Breadcrumbs->add_link('https://jetcraf...', NULL)
#1 /var/www/html/wp-content/plugins/slim-seo/src/Schema/Types/BreadcrumbList.php(12): SlimSEO\Breadcrumbs->parse()
#2 /var/www/html/wp-content/plugins/slim-seo/src/Schema/Types/Base.php(41): SlimSEO\Schema\Types\BreadcrumbList->is_active()
#3 /var/www/html/wp-content/plugins/slim-seo/src/Schema/Manager.php(75): SlimSEO\Schema\Types\Base->add_reference('breadcrumb', Object(SlimSEO\Schema\Types\BreadcrumbList))
#4 /var/www/html/wp-content/plugins/slim-seo/src/Schema/Manager.php(30): SlimSEO\Schema\Manager->add_schemas()
#5 /var/www/html/wp-includes/class-wp-hook.php(324): SlimSEO\Schema\Manager->out

- God bless you and your family.
from Jetcraft.io (Hyunhwa Jeong) Seoul, South Korea.

**Comment by CodingBunnyDev** [comment]
I have a similar problem, but not with Elementor. With breadcrumbs off and schema on, the site breaks. I have to turn both on or off to not have problems. Debug reports a woocommerce compatibility error in a string: thrown in /home/xxxx/public_html/wp-content/plugins/slim-seo/src/Integrations/WooCommerce.php on line 36
[16-Nov-2024 19:07:06 UTC] The WC_Cart::get_remove_url function is deprecated since version 3.3. Replace with wc_get_cart_remove_url.

Translated with [DeepL.com](https://www.deepl.com/?utm_campaign=product&utm_source=web_translator&utm_medium=web&utm_content=copy_free_translation) (free version)

**Comment by rilwis** [comment]
Thanks for your feedback. It's fixed in #171
