### ISSUE TITLE
How to develop locally?

### ISSUE THREAD

**Issue by jayhybrid** [elightup/slim-seo#18]
Sorry if I'm making an obvious mistake but I'm trying to learn this right. I cloned your repo and ran into errors after activating the plugin. Is this a mistake or am I doing something wrong?

```
( ! ) Fatal error: require(): Failed opening required '[...]/slim-seo/vendor/autoload.php' (include_path='.;C:\php\pear') in [...]/slim-seo\slim-seo.php on line 21
```

**Comment by rilwis** [comment]
When developing locally, you need to install Composer and run `composer install` in the plugin folder.

See more about Composer here: https://getcomposer.org/
