### ISSUE TITLE
SlimSEO causes Plugin to load twice?

### ISSUE THREAD

**Issue by grandeljay** [elightup/slim-seo#28]
I am developing a private WP Plugin and with it I am displaying some HTML via a shortcode.

When I activate SlimSEO I noticed that the Shortcode Hook is being called twice, causing my plugin to bork. Basically I just `var_dump` the `$content` in the shortcode callback and with SlimSEO it happens twice.

Do you have any information on this? How can I make SlimSEO and my plugin harmonise? Thanks!

**Comment by rilwis** [comment]
Please [see this docs](https://wpslimseo.com/docs/troubleshooting/).

**Comment by grandeljay** [comment]
Thanks!

But does this mean SlimSEO is not generating a meta description for the page with the shortcode?

**Comment by rilwis** [comment]
Yes, it still does. The filter only makes Slim SEO not parse that shortcode.
