### ISSUE TITLE
Proposal - prioritization for articles and pages…

### ISSUE THREAD

**Issue by Bigblock** [elightup/slim-seo#30]
Hi,

it would be very nice to have the option to priorize an article or a page.

For example from 0.1 to 1.0, so that the search engine can see what's important and what's not.

So why not add a field to each page and article where you can priorize that content, write it to the data base and render it to the xml sitemap.

**Comment by rilwis** [comment]
Google doesn’t use the priority in the sitemap, so let’s close this issue:

https://developers.google.com/search/docs/crawling-indexing/sitemaps/build-sitemap
