### ISSUE TITLE
Plugin shortcode blank even after using slim_seo_skipped_shortcodes filter

### ISSUE THREAD

**Issue by grandeljay** [elightup/slim-seo#32]
So I created a plugin a long time ago and for a while it worked with Slim SEO. Since recently the shortcode page is just blank though. I noticed it after updating my theme (Divi) but I also noticed that my plugin works again after deactivating Slim SEO.

Could Divi / the Divi theme shortcodes be an issue? The page seems to render just fine, it's just my plugin shortcode that is blank.

As mentioned in the title, i've tried using the `slim_seo_skipped_shortcodes` filter to add my shortcode but it didn't help.

Any ideas what I can do to make it work again?

**Comment by grandeljay** [comment]
After some more testing I was able to find that the disables features listed here are breaking my shortcode.

* Mata descriptions
* Open Graph

![image](https://user-images.githubusercontent.com/45571053/142399684-a95a7bf0-cb1b-40e9-b8a0-13337c3ef6fa.png)

**Comment by rilwis** [comment]
Hi @grandeljay 

Thanks for your feedback. Yes, DIVI shortcodes might be the problem. The filter `slim_seo_skipped_shortcodes` is used to eliminate them from auto-generating meta description. Can you share the shortcodes you're using with DIVI and the code that you used with `slim_seo_skipped_shortcodes`?

**Comment by grandeljay** [comment]
I actually didn't think of adding a divi shortcode yet, I just tried my own plugin shortcode. 

It works now after adding the `et_pb_code` shortcode (that's the module I am using to display the shortcode)

I added the code directly into my plugins code rather than the `functions.php`
```php
add_filter( 'slim_seo_skipped_shortcodes', function( $shortcodes ) {
    $shortcodes[] = 'et_pb_code';

    return $shortcodes;
}, 1 );
```

Thanks!
