### ISSUE TITLE
Add noindex status in admin columns and quick edit

### ISSUE THREAD

**Issue by yankiara** [elightup/slim-seo#43]
Hi,

First, congratulations for this plugin. I love light and simple :-)

I would really like to have noindex status in admin columns and quick edit box, especially for pages, since most of the time a lot of pages don't need to be indexed. It would be easier to check/update. And I guess it's not too much bloat. I hate bloat.

Thanks is advance!
Yan

**Comment by d19dotca** [comment]
As I trial out Slim SEO in possibly moving away from Rank Math Pro (I find I don't really use many of the features of it so the cost isn't quite worth it for my clients), I certainly miss the ability to bulk-edit meta title & description and index / noindex status in the Pages and Posts lists. Hopefully this can be added in the near future.

**Comment by rilwis** [comment]
This is done in the recent version of Slim SEO. Please update and try it.
