### ISSUE TITLE
Divi theme issue

### ISSUE THREAD

**Issue by zimivanende** [elightup/slim-seo#50]
Open Graph and Meta description make components disappear.
Look at the video at https://b-smart.team/bijverdienen/

This video disappears when I enable one of the above or both. Divi support says I have to contact you (which is bad support from their side), so hoping someone can fix this.

**Comment by rilwis** [comment]
Fixed in a07563f26a3ca38e673fbf143228e3dc20a6f00b. Please try and let me know if you have any issues.

The new version will be released soon.
