### ISSUE TITLE
Cannot add/edit link in gutenberg on WP 6.0.3

### ISSUE THREAD

**Issue by Lupul** [elightup/slim-seo#78]
With SlimSEO plugin active I get this Error when editing or adding a link in the Gutenberg Editor (Disabling the plugin fixes the problem):
`This block has encountered an error and cannot be previewed.`

![image](https://user-images.githubusercontent.com/3596864/225675211-e5b88b45-b371-46a9-9ad0-6517e69f3f83.png)

The console is logging this error:
```js
TypeError: t.useAnchor is not a function

/wp-content/plugins/slim-seo/js/link-attributes/block-editor/dist/index.js?ver=ae57979e6de9bb251ee7:1
....
```
Context:
useAnchor hook was added in Gutenberg [14.2.0](https://github.com/WordPress/gutenberg/releases/tag/v14.2.0) and WP 6.1

Slim SEO version 3.18.1
WP version 6.0.3

**Comment by rilwis** [comment]
Thank you for your feedback. Let us check this issue and will fix it asap.

**Comment by rilwis** [comment]
Hi @Lupul ,

I can't replicate the bug. I use WP 6.1.1 and tried with and without installing the independent Gutenberg plugin, but it works fine to me. Please see this video:

https://monosnap.com/file/vrzv1VQTvboWbEQpSmJrY8ldjKcjiz

**Comment by Lupul** [comment]
Hello, thanks for taking a look.

The problem happens when running on wp 6.0.3

https://ine-frenzy-yono.instawp.xyz/wp-admin/
user: `caliluvako6910`
pass: `ZSFDbLgujc2Xo1QaKfR8`

https://user-images.githubusercontent.com/3596864/226236554-ee7f552f-b5ae-43b5-8367-5b7141158c77.mp4

**Comment by rilwis** [comment]
Thanks a lot for your feedback. I've fixed it and tested on your site. Please try again.

**Comment by Lupul** [comment]
Awesome, I have tested before instawp session expired and it was fixed.
Thank you.
