### ISSUE TITLE
Illegal string offset 'url' in line 73 of PostType.php

### ISSUE THREAD

**Issue by robinkooli** [elightup/slim-seo#8]
PHP Warning:  Illegal string offset 'url' in ~/wp-content/plugins/slim-seo/src/Sitemaps/PostType.php on line 73

**Comment by rilwis** [comment]
Hi @robinkooli ,

I can't replicate this bug. Looks like it's fixed somehow.

I'll close this issue. Feel free to re-open it if you still see the bug.

Thanks.
