### ISSUE TITLE
Multiple messages when using Very Simple Contact Form

### ISSUE THREAD

**Issue by Imerion** [elightup/slim-seo#9]
Hi!

Thanks for this great plugin! I've been using it a short while and things seem to work fine. I have one problem though: On my page I use a plugin called Very Simple Contact Form (https://wordpress.org/plugins/very-simple-contact-form/) and when Slim SEO is active, each mail from the contact form is sent four times for some reason. Any idea about this? It works normally again if I disable the plugin.

**Comment by rilwis** [comment]
Hi @Imerion 

Sorry for the delay. I've just fixed this issue. Thanks for your feedback!
